### ISSUE TITLE
SSLv3 POODLE mitigation breaks CloudFront caching

### ISSUE THREAD

**Issue by fancyremarker** [aptible/docker-nginx#42]
For some reason, the changes in #41 prevent CloudFront from caching responses from Aptible VHOSTs. My initial hypothesis is that CloudFront's edge servers are using a very narrow (possibly outdated) set of ciphers when making requests to origin servers.

```
ERROR
The request could not be satisfied.

CloudFront wasn't able to connect to the origin. 
Generated by cloudfront (CloudFront)
```

**Comment by steakchaser** [comment]
Here are the two refs to ciphers that I found while troubleshooting:
* [StackOverflow issue with cipher solution](http://stackoverflow.com/questions/20664018/cloudfront-custom-origin-distribution-returns-502-error-the-request-could-not-b)
* [AWS docs detailing supported ciphers](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html)

**Comment by fancyremarker** [comment]
Anyone still seeing this bug: run `aptible restart` to load the most recent version of the `quay.io/aptible/nginx` Docker image.
