### ISSUE TITLE
Additional mime types for gzip support.

### ISSUE THREAD

**Issue by bovee** [aptible/docker-nginx#55]
It would be great to have:
```nginx
gzip_types application/json application/javascript text/css;
```
enabled alongside `gzip on;` to support nginx-level gzipping of files besides html; perhaps more mime types depending on others' use cases.

**Comment by boydgreenfield** [comment]
@chasballew – this is the issue I referenced yesterday. In general, it's my understanding that it's safe to have this turned on for all modern clients, and that clients that do not support compression can also be supported with the `gunzip` option:

```
server {
    gzip on;
    gzip_min_length 1000;
    gunzip on;
    ...
}
```

We serve some quite large JSON responses, so the savings on our end would be significant. More info here: https://www.nginx.com/resources/admin-guide/compression-and-decompression/

**Comment by dtmunir** [comment]
+1

**Comment by fancyremarker** [comment]
This has been released. To use it in your apps, run aptible restart to pick up the latest NGiNX image.

**Comment by dtmunir** [comment]
Thanks Frank. It's working! Really appreciate the quick turnaround here
