### ISSUE TITLE
Set X-Request-Start header to aid in New Relic request queue instrumentation

### ISSUE THREAD

**Issue by fancyremarker** [aptible/docker-nginx#57]
https://docs.newrelic.com/docs/apm/applications-menu/features/request-queue-server-configuration-examples#nginx

**Comment by phanle** [comment]
Did you guys do it over the weekend? Request queue time hasn't shown up on NewRelic for us.

**Comment by fancyremarker** [comment]
@phanle: this has been released. To use it in your apps, run `aptible restart` to pick up the latest NGiNX image.
