### ISSUE TITLE
X-Forwarded-Proto always set to https

### ISSUE THREAD

**Issue by cancan101** [aptible/docker-nginx#60]
Right now `X-Forwarded-Proto` is always set to `https` even though Aptible will listen on `http`.

**Comment by fancyremarker** [comment]
@cancan101: How are you reproducing this? `X-Forwarded-Proto` should only be set [in the server that's listening on 443](https://github.com/aptible/docker-nginx/blob/204dc63/templates/etc/nginx/sites-enabled/server.conf.erb#L75), not the one listening on 80.

**Comment by cancan101** [comment]
Issue would be if I have an nginx service that received on traffic on `http` / `80` but then connects to `upstream` on `https`. Assuming the upstream is a private VHOST, it should be able to trust the `X-Forwarded-Proto` set by nginx. Right now I think that `X-Forwarded-Proto` will be set to https even though the user connected originally to the nginx on `http`.
