### ISSUE TITLE
X-Forwarded-For not being set to client's IP

### ISSUE THREAD

**Issue by cancan101** [aptible/docker-nginx#63]
These directives:

``` nginx
  set_real_ip_from 0.0.0.0/0;
  real_ip_header proxy_protocol;
...
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

do not seem to pass through the original client IP from ELB's proxy protocol.

See for example:
- http://spicefactory.co/blog/2015/09/17/aws-elb-wss/
- https://www.nginx.com/resources/admin-guide/proxy-protocol/

which suggest setting `X-Forwarded-For` differently.

at the very least you want:

``` nginx
proxy_set_header  X-Real-IP           $proxy_protocol_addr;
```

**Comment by fancyremarker** [comment]
@cancan101: Do you have an example app where you're not seeing headers set? This configuration is known to work, so perhaps there's something else happening with your specific app?
