### ISSUE TITLE
Switch to Nginx mainline?

### ISSUE THREAD

**Issue by krallin** [aptible/docker-nginx#74]
We're currently using a rather old version of Nginx (from stable), and #73 updates us to a newer one, but sticks to stable.

However, Nginx appears to recommend using mainline instead (see e.g. http://serverfault.com/questions/715049/what-s-the-difference-between-the-mainline-and-stable-branches-of-nginx for reference).

Should we update to mainline? This would probably be a pre-requisite for supporting HTTP2 anyway.

cc @fancyremarker  @blakepettersson

**Comment by fancyremarker** [comment]
Thanks for the links @krallin. I'd agree that we should update to mainline.

**Comment by blakepettersson** [comment]
I'm for it as well.
